<h1>Novo Livro</h1>

<?php

    $form = $this->form;

    $form->setAttribute('action', $this->url('livraria-admin', array('controller' => 'livros', 'action' => 'new')));
    $form->setAttribute('class', "form-horizontal");

    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <label for="nome">Nome</label>
        <?= $this->formRow($form->get('nome')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <label for="nome">Categoria</label>
        <?= $this->formRow($form->get('categoria')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <label for="nome">Autor</label>
        <?= $this->formRow($form->get('autor')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <label for="nome">Valor</label>
        <?= $this->formRow($form->get('valor')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <label for="nome">ISBN</label>
        <?= $this->formRow($form->get('isbn')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-xs-12 col-md-6">
        <?= $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php
    echo $this->form()->closeTag();
?>