<h1>Users</h1>
<br />


<a href="<?=$this->url('livraria-admin', array('controller' => 'users', 'action' => 'new'))?>" class="btn btn-primary">New</a>

<br/><br/>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Ação</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->data as $entity): ?>
            <tr>
                <td><?=$entity->getId()?></td>
                <td><?=$entity->getNome()?></td>
                <td><?=$entity->getEmail()?></td>
                <td>
                    <a href="<?=$this->url('livraria-admin-interna', array('controller' => 'users', 'action' => 'edit', 'id' => $entity->getId()))?>" class="btn btn-info">Edit</a>
                    <a href="<?=$this->url('livraria-admin-interna', array('controller' => 'users', 'action' => 'delete', 'id' => $entity->getId()))?>" class="btn btn-danger">Remove</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?= $this->paginationControl($this->data, 'Sliding', 'paginator') ?>